// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1i3M3zH57GHaMHu3jypIMwjTlA9AhWt0',
    appId: '1:441938722137:web:cd84c58e4741a2bfdb6048',
    messagingSenderId: '441938722137',
    projectId: 'ostad10',
    authDomain: 'ostad10.firebaseapp.com',
    databaseURL: 'https://ostad10-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad10.firebasestorage.app',
    measurementId: 'G-74S4B51200',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACd6me87cNTgauJy7abpAfQdm-GmMP36I',
    appId: '1:441938722137:android:7a420c7dbc7ecacedb6048',
    messagingSenderId: '441938722137',
    projectId: 'ostad10',
    databaseURL: 'https://ostad10-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1PKidSQmRcTJYhuxTYkEBe2mRLzvzAs',
    appId: '1:441938722137:ios:e06a2f7e3f05bee1db6048',
    messagingSenderId: '441938722137',
    projectId: 'ostad10',
    databaseURL: 'https://ostad10-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad10.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1PKidSQmRcTJYhuxTYkEBe2mRLzvzAs',
    appId: '1:441938722137:ios:e06a2f7e3f05bee1db6048',
    messagingSenderId: '441938722137',
    projectId: 'ostad10',
    databaseURL: 'https://ostad10-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad10.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1i3M3zH57GHaMHu3jypIMwjTlA9AhWt0',
    appId: '1:441938722137:web:cc437f3f69dca6acdb6048',
    messagingSenderId: '441938722137',
    projectId: 'ostad10',
    authDomain: 'ostad10.firebaseapp.com',
    databaseURL: 'https://ostad10-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad10.firebasestorage.app',
    measurementId: 'G-V57PPMKYR7',
  );
}
